version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      # PostgreSQL database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      # Add PostgreSQL database as a data source
      PG_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      # Enable the Hasura console
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # Enable development mode
      HASURA_GRAPHQL_DEV_MODE: "true"
      # Enable logging
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: